blueprint:
  name: ZBMINIR2 detached relay mode
  description: Configure ZBMINIR2 to toggle light without turn off the switch.
  domain: automation
  author: Philipp Klüter
  homeassistant:
    min_version: 25.12.0

  input:
    zbminir2_device:
      name: ZBMINIR2 device
      description: ZBMINIR2 device, ensure to activate "Detach relay mode"
      selector:
        device:
          filter:
            manufacturer: SONOFF
            model: Zigbee smart switch
          multiple: false

    controlled_light:
      name: Toggle target lights
      description: The switch will toggle these lights.
      selector:
        entity:
          filter:
            domain: light
          multiple: true

triggers:
  - domain: binary_sensor
    device_id: !input "zbminir2_device"
    type: opened
    trigger: device

variables:
  zbminir2_device: !input "zbminir2_device"
  zbminir2_switch: "{{ device_entities(zbminir2_device)[0] }}"

actions:
  sequence:
    - action: light.toggle
      metadata: {}
      data: {}
      target:
        entity_id: !input "controlled_light"

mode: single
