blueprint:
  name: ZBMINIR2 detached relay mode
  description: Configure ZBMINIR2 to toggle light without turn off the switch.
  domain: automation
  author: Philipp Klüter
  source_url: https://git.klueter.dev/ThronRycer/HomeAssistant/raw/branch/main/blueprints/sonoff/zbminir2-detached.yaml

  input:
    zbminir2_entity:
      name: ZBMINIR2 input
      description: Binary sensor of the ZBMINIR2 (detach relay mode)
      selector:
        entity:
          filter:
            domain: binary_sensor
            device_class: opening
          multiple: false

    controlled_light:
      name: Toggle target lights
      description: The switch will toggle these lights.
      selector:
        entity:
          filter:
            domain: light
          multiple: true

triggers:
  - platform: state
    entity_id: !input zbminir2_entity
    from: "off"
    to: "on"

actions:
  sequence:
    - action: light.toggle
      metadata: {}
      data: {}
      target:
        entity_id: !input "controlled_light"

mode: single
