blueprint:
  name: Motion-activated Light with Lux Sensor
  description: Turn on a light when motion is detected and lux is below a threshold.
  domain: automation
  author: Philipp Klüter
  source_url: https://git.klueter.dev/ThronRycer/HomeAssistant/raw/branch/main/blueprints/lights/motion-activated-with-lux-sensor.yml

  input:
    motion_entity:
      name: Motion Sensor
      selector:
        entity:
          filter:
            domain: binary_sensor
            device_class:
              - motion
              - occupancy

    light_target:
      name: Light
      selector:
        target:
          entity:
            domain: light

    disabled_when_on:
      name: Disabled when on
      description: The motion activation is disabled when one of these lights is on.
      selector:
        entity:
          filter:
            domain: light
          multiple: true
      default: []

    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default: 10
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds

    lux_entity:
      name: Illuminance Sensor
      selector:
        entity:
          filter:
            domain: sensor
            device_class: illuminance

    lux_threshold:
      name: Illuminance threshold
      default: 5
      selector:
        number:
          min: 0
          max: 200
          unit_of_measurement: lux

mode: restart
max_exceeded: silent

triggers:
  - trigger: state
    entity_id: !input motion_entity
    to: "on"

conditions:
  # Only checked when motion turns ON
  - condition: numeric_state
    entity_id: !input lux_entity
    below: !input lux_threshold

  - condition: state
    entity_id: !input disabled_when_on
    state: "off"

actions:
  - alias: Turn on the light
    action: light.turn_on
    target: !input light_target

  - alias: Wait until motion is off for the configured time
    wait_for_trigger:
      - trigger: state
        entity_id: !input motion_entity
        to: "off"
        for:
          seconds: !input no_motion_wait

  - alias: Turn off the light
    action: light.turn_off
    target: !input light_target
